name: Deploy Rustdoc to GitHub Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build documentation
        run: cargo doc --no-deps --document-private-items
      - name: Add index.html redirect
        run: echo '<meta http-equiv="refresh" content="0; url=easy-sat-rs/index.html">'
          > target/doc/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./target/doc

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
